### ISSUE TITLE
Xiaomi Smart Air Purifier 4 Lite - Wiki update

### ISSUE THREAD

**Issue by smogger** [dhewg/esphome-miot#13]
Any chance to get a bit more details about the Xiaomi Smart Air Purifier 4 Lite steps?

I am trying to get my heads around with the "power on the board" step. 

I tried either power on the whole unit (3 beeps from the purifier and not connecting to my UART) - since nowhere mentioned HOW should we power on the board. 
And also tried directly connecting the 3V from my UART to the ESP32 chip leg (still not connecting somehow for me)

The board layout is slightly different then the previous version, so those guides doesn't really help me with the 4 Lite. 

(PS: strange to me that whenever I plug the TX/RX to my UART, the power led lights up on it)

Thank you

**Comment by helgek** [comment]
I flashed directly on the chip using Sensepeek PCBite while the device wasn't connected to power. Instead I used the 3.3V coming from the UART device. I had tried the test pins before as outlined in the guide but when it didn't work immediately I didn't want to invest more time to figure out this variant, instead I went straight on the esp32 pins. I've already flashed about seven devices like this (mostly yeelight lamps and one other xiaomi light).

![image](https://github.com/dhewg/esphome-miot/assets/6280991/4b527b8d-81c2-46ac-9051-e04d2062b39a)

**Comment by dhewg** [comment]
Does reading from uart work when the device is running the vendor fw? You should see it logging. That needs to work first, and only then can you attempt to flash a new fw.

In my case, I just powered the whole board with its standard power supply. Powering only the esp would be safer, but not as easy. Powering the esp via your uart ttl adapter might not work, depending on how reliable the power output is (you might get lucky, but assume it's not sufficient).

And is that really another revision of the rmb1 or the newer rma2 version (#14)?

**Comment by smogger** [comment]
> In my case, I just powered the whole board with its standard power supply.


How were you been able to power on the board? In my case when I disassembled I had to unplug the display or the sensor from the board (i dont remember now) otherwise I had not enough space/long cable to remove it from the outer shell to have access to the testpoints. And without the sensor I cannot power on the board as it just beeps 3-4 times and thats it.

**Comment by smogger** [comment]
> Does reading from uart work when the device is running the vendor fw? You should see it logging. That needs to work first, and only then can you attempt to flash a new fw.
  
Esphome (HA) does such thing? Honestly never tried to read out this way. I programmed blank esps only.

**Comment by dhewg** [comment]
> How were you been able to power on the board? In my case when I disassembled I had to unplug the display or the sensor from the board

Same here, I detached various connectors to get to the board, but reattached them once I disassembled the device. So the wires temporarily had different paths, but the device as a whole was fully functioning.

> Esphome (HA) does such thing?

Either firmware will log over uart, but in this case I meant the original vendor firmware. It's just to confirm that uart is working. Because if it's not there's no way you can flash another firmware over uart (duh ;)

**Comment by helgek** [comment]
To back up:
`esptool.py --baud 57600 --port /dev/cu.usbserial-110 read_flash 0x00000 0x400000 fwbackup_xyz.bin   `

To compile:
`esptool.py compile airpurifier.yaml  `

To flash:
esptool.py --baud 115200  --port /dev/cu.usbserial-110 write_flash --flash_size detect 0x00000  firmware-factory.bin

With automatic port detection this might also work instead:
`esphome run airpurifier.yaml`

**Comment by smogger** [comment]
In some cases, one of my purifier lose Wifi connection. 

I added the following line to the code, but it seem doesnt really reset the ESP upon disconnect. 

"wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 15min
 "

Am I missing something??

**Comment by w-marco** [comment]
@helgek do you happen to have the backup firmware file for the purifier? I lost mine and want to archive it.

**Comment by helgek** [comment]
[fwbackup_air_purifier_4_lite.bin.zip](https://github.com/user-attachments/files/16385101/fwbackup_air_purifier_4_lite.bin.zip)

 @w-marco 
This is the backup file. You probably are aware that there are two versions of this device: zhimi.airp.rmb1 and zhimi.airp.rma2

The backup file is for the zhimi.airp.rmb1 version. I assume you have the same device variant since you probably wouldn't have been able to flash the device with a working config otherwise. I think for the zhimi.airp.rma2 there isn't a working ESPHome based configuration available yet. But it's been a while since I flashed this device so I don't remember the details anymore at the moment.

**Comment by w-marco** [comment]
Thanks, yes I have rmb1, so it's the one I need!

**Comment by dhewg** [comment]
This should be resolved, closing. Let me know if I missed anything!
